# Generated by Django 2.0.6 on 2018-06-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180621_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
