# Generated by Django 2.0.6 on 2018-09-18 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=500)),
                ('about', models.TextField(max_length=200000)),
                ('download_link', models.URLField(max_length=500)),
                ('version', models.CharField(max_length=200)),
                ('supported_device', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('homepage', models.URLField(max_length=500)),
                ('info', models.TextField(max_length=200000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('category', models.CharField(choices=[('Communications and Language', 'Communications and Language'), ('Search & Discovery', 'Search & Discovery'), ('Documents', 'Documents'), ('News', 'News'), ('Chat, mail and talk', 'Chat, mail and talk'), ('Media creation', 'Media creation'), ('Programming', 'Programming'), ('Maths & Science', 'Maths & Science'), ('Maps & Geography', 'Maps & Geography'), ('Media players', 'Media players'), ('Games', 'Games'), ('Teacher tools', 'Teacher tools'), ('Utilities', 'Utilities'), ('Web', 'Web'), ('collections', 'collections'), ('NA', 'NA')], default='NA', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
